# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddd42afb308d3b37d2c45248474a4cb76af9113dad8d8f417d15662a1dc69b68ed76e32f664fa5357d278ac8a03f0ec481c89719f9db7f4207dd5b71b4fc200

test:
  secret_key_base: d5ffc37da88547a81103e20ba48de0f0957e0503346cf6acf24bf918c3bce021ec19540cb50c9b7048935e6a8a2dd262f41b1800e98e9b85c14e46829e584455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
